/**
 * ASSET MANIFEST FOR BROKOLI KAHRAMAN
 * Matches the newly cleaned standalone PNG files in public/assets/brokoli/
 */

export interface AssetMapping {
  key: string;
  path: string;
  width: number;
  height: number;
  category: 'brand' | 'player' | 'friend' | 'boss' | 'world' | 'platform' | 'environment' | 'ui';
  purpose: string;
}

export const ASSET_MANIFEST: Record<string, AssetMapping> = {
  // 01 BRAND
  feature_banner: {
    key: 'feature_banner',
    path: '/assets/brokoli/01_brand/feature_banner.png',
    width: 375,
    height: 115,
    category: 'brand',
    purpose: 'Main menu banner and brand visual identity',
  },
  android_icon: {
    key: 'android_icon',
    path: '/assets/brokoli/01_brand/android_icon.png',
    width: 115,
    height: 115,
    category: 'brand',
    purpose: 'Game icon',
  },

  // 02 CHARACTERS (HERO & RESCUE FRIENDS)
  brokoli_kahraman: {
    key: 'brokoli_kahraman',
    path: '/assets/brokoli/02_characters/brokoli_kahraman.png',
    width: 512,
    height: 544,
    category: 'player',
    purpose: 'Brokoli Hero with red cape and gold belt',
  },
  havuc_kiz_arkadas: {
    key: 'havuc_kiz_arkadas',
    path: '/assets/brokoli/02_characters/havuc_kiz_arkadas.png',
    width: 110,
    height: 127,
    category: 'friend',
    purpose: 'Carrot girlfriend trapped in castle; grand finale rescue partner',
  },
  domates: {
    key: 'domates',
    path: '/assets/brokoli/02_characters/domates_dost.png',
    width: 113,
    height: 129,
    category: 'friend',
    purpose: 'Rescuable vegetable friend: Domates Dost (World 1)',
  },
  biber: {
    key: 'biber',
    path: '/assets/brokoli/02_characters/biber_dost.png',
    width: 73,
    height: 130,
    category: 'friend',
    purpose: 'Rescuable vegetable friend: Biber Dost (World 1)',
  },
  misir: {
    key: 'misir',
    path: '/assets/brokoli/02_characters/misir_dost.png',
    width: 108,
    height: 130,
    category: 'friend',
    purpose: 'Rescuable vegetable friend: Mısır Dost (World 2)',
  },
  sogan: {
    key: 'sogan',
    path: '/assets/brokoli/02_characters/sogan_dost.png',
    width: 104,
    height: 127,
    category: 'friend',
    purpose: 'Rescuable vegetable friend: Soğan Dost (World 2)',
  },
  patlican: {
    key: 'patlican',
    path: '/assets/brokoli/02_characters/patlican_dost.png',
    width: 109,
    height: 120,
    category: 'friend',
    purpose: 'Rescuable vegetable friend: Patlıcan Dost (World 3)',
  },
  salatalik: {
    key: 'salatalik',
    path: '/assets/brokoli/02_characters/salatalik_dost.png',
    width: 84,
    height: 120,
    category: 'friend',
    purpose: 'Rescuable vegetable friend: Salatalık Dost (World 3)',
  },
  bezelye: {
    key: 'bezelye',
    path: '/assets/brokoli/02_characters/bezelye_dost.png',
    width: 78,
    height: 114,
    category: 'friend',
    purpose: 'Rescuable vegetable friend: Bezelye Dost (World 4)',
  },
  mantar: {
    key: 'mantar',
    path: '/assets/brokoli/02_characters/mantar_dost.png',
    width: 101,
    height: 110,
    category: 'friend',
    purpose: 'Rescuable vegetable friend: Mantar Dost (World 4)',
  },

  // 03 ENEMIES & BOSSES
  hamburger_krali: {
    key: 'hamburger_krali',
    path: '/assets/brokoli/03_enemies_bosses/hamburger_krali.png',
    width: 238,
    height: 175,
    category: 'boss',
    purpose: 'Final Boss (World 5): Giant Hamburger King with crown and cape',
  },
  ketcap: {
    key: 'ketcap',
    path: '/assets/brokoli/03_enemies_bosses/ketcap.png',
    width: 140,
    height: 175,
    category: 'boss',
    purpose: 'World 1 Boss: Ketchup Bottle Boss',
  },
  hardal: {
    key: 'hardal',
    path: '/assets/brokoli/03_enemies_bosses/hardal.png',
    width: 141,
    height: 175,
    category: 'boss',
    purpose: 'World 2 Boss: Mustard Bottle Boss',
  },
  mayonez: {
    key: 'mayonez',
    path: '/assets/brokoli/03_enemies_bosses/mayonez.png',
    width: 130,
    height: 175,
    category: 'boss',
    purpose: 'World 3 Boss: Mayonnaise Jar Boss',
  },

  // 04 WORLDS
  world_01_yesil_vadi: {
    key: 'world_01_yesil_vadi',
    path: '/assets/brokoli/04_worlds/world_01_yesil_vadi.png',
    width: 189,
    height: 175,
    category: 'world',
    purpose: 'World 1 (Yeşil Vadi) panoramic backdrop',
  },
  world_02_ciftlik_bolgesi: {
    key: 'world_02_ciftlik_bolgesi',
    path: '/assets/brokoli/04_worlds/world_02_ciftlik_bolgesi.png',
    width: 129,
    height: 175,
    category: 'world',
    purpose: 'World 2 (Çiftlik Bölgesi) panoramic backdrop',
  },
  world_03_sos_fabrikasi: {
    key: 'world_03_sos_fabrikasi',
    path: '/assets/brokoli/04_worlds/world_03_sos_fabrikasi.png',
    width: 189,
    height: 175,
    category: 'world',
    purpose: 'World 3 (Sos Fabrikası) panoramic backdrop',
  },
  world_04_buzluk_bolgesi: {
    key: 'world_04_buzluk_bolgesi',
    path: '/assets/brokoli/04_worlds/world_04_buzluk_bolgesi.png',
    width: 210,
    height: 175,
    category: 'world',
    purpose: 'World 4 (Buzluk Bölgesi) panoramic backdrop',
  },
  world_05_hamburger_kalesi: {
    key: 'world_05_hamburger_kalesi',
    path: '/assets/brokoli/04_worlds/world_05_hamburger_kalesi.png',
    width: 228,
    height: 175,
    category: 'world',
    purpose: 'World 5 (Hamburger Kalesi) panoramic backdrop',
  },

  // 05 ENVIRONMENT
  zemin_1: {
    key: 'zemin_1',
    path: '/assets/brokoli/05_environment/zemin_1.png',
    width: 100,
    height: 59,
    category: 'platform',
    purpose: 'World 1 Grass Platform',
  },
  zemin_2: {
    key: 'zemin_2',
    path: '/assets/brokoli/05_environment/zemin_2.png',
    width: 98,
    height: 61,
    category: 'platform',
    purpose: 'World 2 Farm Earth Platform',
  },
  zemin_3_buz: {
    key: 'zemin_3_buz',
    path: '/assets/brokoli/05_environment/zemin_3_buz.png',
    width: 88,
    height: 59,
    category: 'platform',
    purpose: 'World 4 Ice Platform',
  },
  zemin_4_fabrika: {
    key: 'zemin_4_fabrika',
    path: '/assets/brokoli/05_environment/zemin_4_fabrika.png',
    width: 79,
    height: 59,
    category: 'platform',
    purpose: 'World 3 Factory Steel Platform',
  },
  zemin_5_kale: {
    key: 'zemin_5_kale',
    path: '/assets/brokoli/05_environment/zemin_5_kale.png',
    width: 94,
    height: 59,
    category: 'platform',
    purpose: 'World 5 Castle Brick Platform',
  },
  hareketli_platform: {
    key: 'hareketli_platform',
    path: '/assets/brokoli/05_environment/hareketli_platform.png',
    width: 120,
    height: 73,
    category: 'platform',
    purpose: 'Moving Platform',
  },
  asansor: {
    key: 'asansor',
    path: '/assets/brokoli/05_environment/asansor.png',
    width: 58,
    height: 78,
    category: 'platform',
    purpose: 'Elevator Platform',
  },
  kafes: {
    key: 'kafes',
    path: '/assets/brokoli/05_environment/kafes.png',
    width: 54,
    height: 78,
    category: 'environment',
    purpose: 'Rescue cage for trapped vegetable friends',
  },
  kilitli_kapi: {
    key: 'kilitli_kapi',
    path: '/assets/brokoli/05_environment/kilitli_kapi.png',
    width: 71,
    height: 77,
    category: 'environment',
    purpose: 'Level exit door',
  },
  anahtar: {
    key: 'anahtar',
    path: '/assets/brokoli/05_environment/anahtar.png',
    width: 62,
    height: 73,
    category: 'environment',
    purpose: 'Collectible key to unlock cages and doors',
  },
  altin_para: {
    key: 'altin_para',
    path: '/assets/brokoli/05_environment/altin_para.png',
    width: 58,
    height: 71,
    category: 'environment',
    purpose: 'Collectible golden coin',
  },
  yildiz: {
    key: 'yildiz',
    path: '/assets/brokoli/05_environment/yildiz.png',
    width: 70,
    height: 71,
    category: 'environment',
    purpose: '3-star ranking reward icon',
  },
  buton: {
    key: 'buton',
    path: '/assets/brokoli/05_environment/buton.png',
    width: 55,
    height: 57,
    category: 'environment',
    purpose: 'Interactive button switch',
  },
  kaldirac: {
    key: 'kaldirac',
    path: '/assets/brokoli/05_environment/kaldirac.png',
    width: 54,
    height: 72,
    category: 'environment',
    purpose: 'Interactive puzzle lever',
  },
  diken: {
    key: 'diken',
    path: '/assets/brokoli/05_environment/diken.png',
    width: 67,
    height: 66,
    category: 'environment',
    purpose: 'Ground sharp spike hazard',
  },
  ahsap_kutu: {
    key: 'ahsap_kutu',
    path: '/assets/brokoli/05_environment/ahsap_kutu.png',
    width: 53,
    height: 76,
    category: 'environment',
    purpose: 'Pushable wooden puzzle box',
  },
  kirilabilir_kutu: {
    key: 'kirilabilir_kutu',
    path: '/assets/brokoli/05_environment/kirilabilir_kutu.png',
    width: 87,
    height: 75,
    category: 'environment',
    purpose: 'Breakable crate obstacle',
  },
  varil: {
    key: 'varil',
    path: '/assets/brokoli/05_environment/varil.png',
    width: 28,
    height: 76,
    category: 'environment',
    purpose: 'Factory sauce barrel',
  },
  kontrol_paneli: {
    key: 'kontrol_paneli',
    path: '/assets/brokoli/05_environment/kontrol_paneli.png',
    width: 82,
    height: 66,
    category: 'environment',
    purpose: 'Factory control panel mechanism',
  },
  yon_oku: {
    key: 'yon_oku',
    path: '/assets/brokoli/05_environment/yon_oku.png',
    width: 70,
    height: 73,
    category: 'environment',
    purpose: 'Direction arrow indicator',
  },

  // 07 UI
  can_icon: {
    key: 'can_icon',
    path: '/assets/brokoli/07_ui/can_icon.png',
    width: 31,
    height: 41,
    category: 'ui',
    purpose: 'Heart health HUD icon',
  },
  para_icon: {
    key: 'para_icon',
    path: '/assets/brokoli/07_ui/para_icon.png',
    width: 55,
    height: 61,
    category: 'ui',
    purpose: 'Coin HUD counter icon',
  },
  yildiz_icon: {
    key: 'yildiz_icon',
    path: '/assets/brokoli/07_ui/yildiz_icon.png',
    width: 50,
    height: 54,
    category: 'ui',
    purpose: 'Star rating HUD icon',
  },
  anahtar_icon: {
    key: 'anahtar_icon',
    path: '/assets/brokoli/07_ui/anahtar_icon.png',
    width: 50,
    height: 64,
    category: 'ui',
    purpose: 'Key indicator HUD icon',
  },
  duraklat_icon: {
    key: 'duraklat_icon',
    path: '/assets/brokoli/07_ui/duraklat_icon.png',
    width: 33,
    height: 44,
    category: 'ui',
    purpose: 'Pause button HUD icon',
  },
};
